name: Build New Version

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: git config
              run: |
                git config user.name "${GITHUB_ACTOR}"
                git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

            - name: Install Dependencies
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm install
            - run: npm run build
            - run: npm test
            - run: npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
