name: Build New Version

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Dependencies
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: npm install

            - name: Release new version
              run: npm run build
