name: Build

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Creating .env.production
              uses: SpicyPizza/create-envfile@v1.3
              with:
                envkey_NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
                envkey_NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
                file_name: .env.production
                fail_on_empty: true

            - name: Import GPG key
              id: import_gpg
              uses: crazy-max/ghaction-import-gpg@v5
              with:
                  git_user_signingkey: true
                  git_tag_gpgsign: true
                  git_commit_gpgsign: true
                  gpg_private_key: ${{ secrets.SIGN_GPG_KEY }}
                  passphrase: ${{ secrets.SIGN_GPG_PASS }}

            - name: git config
              run: |
                git config user.name "${GITHUB_ACTOR}"
                git config user.email "attilagyongyosi0@gmail.com"

            - name: Install Dependencies
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
            - run: npm ci
            - run: npm test
            - run: npm run build
            - run: npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
