name: Release latest version to Prod

on: workflow_dispatch

env:
    NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
    NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Install Dependencies
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   run: npm ci
            -   run: npm run build

            -   name: Deploying Artifact to SLS Prod Stage
                id: sls-deploy-prod
                run: npm run deploy:prod
                env:
                    SERVERLESS_ACCESS_KEY: ${{ secrets.SLS_ACCESS_KEY }}
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

