name: Release latest version to Dev

on:
    workflow_run:
        workflows: [Build]
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: get-npm-version
                id: package-version
                uses: martinbeentjes/npm-get-version-action@main

            -   uses: actions/download-artifact@v3
                with:
                    name: blog-build-${{ steps.package-version.outputs.current-version }}

            -   name: Deploying Artifact to SLS Prod Stage
                id: sls-deploy-dev
                run: npm run deploy:dev
                env:
                    SERVERLESS_ACCESS_KEY: ${{ secrets.SLS_ACCESS_KEY }}
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

