name: Release latest version to Prod

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Fetching current NPM package version
                id: package-version
                uses: martinbeentjes/npm-get-version-action@main

            -   name: Installing Serverless Components CLI for Deployment
                uses: actions/setup-node@v3
                with:
                    node-version: 18
                    cache: 'npm'
            -   run: npm i serverless@3.24.1 @serverless/components@3.18.2

            -   name: Downloading build artifact from Build Workflow
                uses: dawidd6/action-download-artifact@v2
                with:
                    workflow: build.yml
                    name: blog-build-${{ steps.package-version.outputs.current-version }}
                    path: public/

            -   name: Deploying Artifact to SLS Prod Stage
                run: npm run deploy:prod
                env:
                    SERVERLESS_ACCESS_KEY: ${{ secrets.SLS_ACCESS_KEY }}
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

